public class BlockLetterPrinter {
  private static String[][] characters = {
      {" AAA ",
       "A   A",
       "A   A",
       "AAAAA",
       "A   A",
       "A   A",
       "A   A"
      },
      {"BBBB ",
       "B   B",
       "B   B",
       "BBBB ",
       "B   B",
       "B   B",
       "BBBB "  
      },
      {" CCC ",
       "C   C",
       "C    ",
       "C    ",
       "C    ",
       "C   C",
       " CCC "
      },
      {"DDDD ",
       "D   D",
       "D   D",
       "D   D",
       "D   D",
       "D   D",
       "DDDD "
      },
      {"EEEEE",
       "E    ",
       "E    ",
       "EEEEE",
       "E    ",
       "E    ",
       "EEEEE"
      },
      {"FFFFF",
       "F    ",
       "F    ",
       "FFFFF",
       "F    ",
       "F    ",
       "F    "
      },
      {" GGG ",
       "G   G",
       "G    ",
       "G GGG",
       "G   G",
       "G   G",
       " GGG "
      },
      {"H   H",
       "H   H",
       "H   H",
       "HHHHH",
       "H   H",
       "H   H",
       "H   H"
      },
      {"IIIII",
       "  I  ",
       "  I  ",
       "  I  ",
       "  I  ",
       "  I  ",
       "IIIII"
      },
      {"JJJJJ",
       "    J",   
       "    J",
       "    J",
       "    J",
       "    J",
       "JJJJ "
      },
      {"K   K",
       "K  K ",
       "K K  ",
       "KK   ", 
       "K K  ",
       "K  K ",
       "K   K"
      },
      {"L    ",
       "L    ",
       "L    ",
       "L    ",
       "L    ",
       "L    ",
       "LLLLL"
      },
      {"M   M",
       "MM MM",
       "M M M",
       "M   M",
       "M   M",
       "M   M",
       "M   M"
      },
      {"N   N",
       "NN  N",
       "N   N",
       "N N N",
       "N   N",
       "N  NN",
       "N   N"
      },
      {" OOO ",
       "O   O",
       "O   O",
       "O   O",
       "O   O",
       "O   O",
       " OOO "
      },
      {"PPPP ",
       "P   P",
       "P   P",
       "PPPP ",
       "P    ",
       "P    ",
       "P    "
      },
      {" QQQ ",
       "Q   Q", 
       "Q   Q",
       "Q   Q",
       "Q Q Q",
       "Q  QQ",
       " QQQQ"
      },
      {"RRRR ",
       "R   R",
       "R   R",
       "RRRR ",
       "R R  ",
       "R  R ",
       "R   R" 
      },
      {" SSS ",
       "S   S",
       "S    ",
       " SSS ",
       "    S",
       "S   S",
       " SSS "
      },
      {"TTTTT",
       "  T  ",
       "  T  ",
       "  T  ",
       "  T  ",
       "  T  ",
       "  T  "
      },
      {"U   U",
       "U   U",
       "U   U",
       "U   U",
       "U   U",
       "U   U",
       " UUU "
      },
      {"V   V",
       "V   V",
       "V   V",
       "V   V",
       "V   V",
       " V V ",
       "  V  "
      },
      {"W   W",
       "W   W",
       "W   W",
       "W W W",
       "W W W",
       "W W W",
       " W W ",
      },
      {"X   X",
       "X   X",
       " X X ",
       "  X  ",
       " X X ",
       "X   X",
       "X   X"
      },
      {"Y   Y",
       "Y   Y",
       " Y Y ",
       "  Y  ",
       "  Y  ",
       "  Y  ",
       "  Y  "
      },
      {"ZZZZZ",
       "    Z", 
       "   Z ", 
       "  Z  ",
       " Z   ",
       "Z    ",
       "ZZZZZ"
      },
      {"     ",
       "     ",
       "     ",
       "     ",
       "     ",
       "     ",
       "     "
      }
  };
  public static String blockPrint(String string){
    String ret = "";
    string = string.trim().toUpperCase().replace(" ", "[");
    if (string.isEmpty()) return ret;
    char [] str = string.toCharArray();
    for (int rpointer=0; rpointer < 7; ++rpointer) {
      for (char chr : str) {
        ret += characters[chr-'A'][rpointer] + " ";
      }
      ret = ret.stripTrailing() + "\n";
    }
    return ret.substring(0, ret.length()-1);
  }
}
